### ISSUE TITLE
App crashes on Sony Xperia M5, Android 6

### ISSUE THREAD

**Issue by mrgames13** [mrgames13/Feinstaub-App#29]
App crashes on splash screen.

**Comment by mrgames13** [comment]
Android system error logs, catched by using ADB:

> --------- beginning of crash
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: FATAL EXCEPTION: main
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: Process: com.mrgames13.jimdo.feinstaubapp, PID: 25726
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mrgames13.jimdo.feinstaubapp/com.mrgames13.jimdo.feinstaubapp.App.MainActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.miguelcatalan.materialsearchview.MaterialSearchView
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2581)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2647)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5763)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.miguelcatalan.materialsearchview.MaterialSearchView
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at androidx.appcompat.app.g.c()
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at androidx.appcompat.app.d.setContentView()
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at com.mrgames13.jimdo.feinstaubapp.App.MainActivity.onCreate()
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6270)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	... 9 more
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.miguelcatalan.materialsearchview.MaterialSearchView
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	... 17 more
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Native Method)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	... 24 more
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class ImageButton
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at com.miguelcatalan.materialsearchview.MaterialSearchView.g()
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at com.miguelcatalan.materialsearchview.MaterialSearchView.<init>()
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at com.miguelcatalan.materialsearchview.MaterialSearchView.<init>()
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	... 26 more
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #42: Error inflating class ImageButton
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	... 30 more
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f080092
> 08-28 15:04:09.330 25726 25726 E AndroidRuntime: 	at android.content.res.Resources.g
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: FATAL EXCEPTION: main
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: Process: com.mrgames13.jimdo.feinstaubapp, PID: 27491
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mrgames13.jimdo.feinstaubapp/com.mrgames13.jimdo.feinstaubapp.App.MainActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.miguelcatalan.materialsearchview.MaterialSearchView
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2581)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2647)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5763)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.miguelcatalan.materialsearchview.MaterialSearchView
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at androidx.appcompat.app.g.c()
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at androidx.appcompat.app.d.setContentView()
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at com.mrgames13.jimdo.feinstaubapp.App.MainActivity.onCreate()
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6270)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	... 9 more
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.miguelcatalan.materialsearchview.MaterialSearchView
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	... 17 more
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Native Method)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	... 24 more
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class ImageButton
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at com.miguelcatalan.materialsearchview.MaterialSearchView.g()
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at com.miguelcatalan.materialsearchview.MaterialSearchView.<init>()
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at com.miguelcatalan.materialsearchview.MaterialSearchView.<init>()
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	... 26 more
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #42: Error inflating class ImageButton
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	... 30 more
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f080092
> 08-28 15:06:00.552 27491 27491 E AndroidRuntime: 	at android.content.res.Resources.g
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: FATAL EXCEPTION: main
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: Process: com.mrgames13.jimdo.feinstaubapp, PID: 28499
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mrgames13.jimdo.feinstaubapp/com.mrgames13.jimdo.feinstaubapp.App.MainActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.miguelcatalan.materialsearchview.MaterialSearchView
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2581)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2647)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5763)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.miguelcatalan.materialsearchview.MaterialSearchView
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at androidx.appcompat.app.g.c()
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at androidx.appcompat.app.d.setContentView()
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at com.mrgames13.jimdo.feinstaubapp.App.MainActivity.onCreate()
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6270)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	... 9 more
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.miguelcatalan.materialsearchview.MaterialSearchView
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	... 17 more
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Native Method)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	... 24 more
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class ImageButton
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at com.miguelcatalan.materialsearchview.MaterialSearchView.g()
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at com.miguelcatalan.materialsearchview.MaterialSearchView.<init>()
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at com.miguelcatalan.materialsearchview.MaterialSearchView.<init>()
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	... 26 more
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #42: Error inflating class ImageButton
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	... 30 more
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f080092
> 08-28 15:06:48.942 28499 28499 E AndroidRuntime: 	at android.content.res.Resources.g
